// Code generated by girgen. DO NOT EDIT.

package adw

import (
	"fmt"
	"runtime"
	"unsafe"

	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <adwaita.h>
// #include <glib-object.h>
import "C"

// GType values.
var (
	GTypeEasing = coreglib.Type(C.adw_easing_get_type())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeEasing, F: marshalEasing},
	})
}

// Easing describes the available easing functions for use with timedanimation.
//
// New values may be added to this enumeration over time.
type Easing C.gint

const (
	// Linear: linear tweening.
	Linear Easing = iota
	// EaseInQuad: quadratic tweening.
	EaseInQuad
	// EaseOutQuad: quadratic tweening, inverse of adw.Easing.Ease-in-quad.
	EaseOutQuad
	// EaseInOutQuad: quadratic tweening, combining adw.Easing.Ease-in-quad and
	// adw.Easing.Ease-out-quad.
	EaseInOutQuad
	// EaseInCubic: cubic tweening.
	EaseInCubic
	// EaseOutCubic: cubic tweening, inverse of adw.Easing.Ease-in-cubic.
	EaseOutCubic
	// EaseInOutCubic: cubic tweening, combining adw.Easing.Ease-in-cubic and
	// adw.Easing.Ease-out-cubic.
	EaseInOutCubic
	// EaseInQuart: quartic tweening.
	EaseInQuart
	// EaseOutQuart: quartic tweening, inverse of adw.Easing.Ease-in-quart.
	EaseOutQuart
	// EaseInOutQuart: quartic tweening, combining adw.Easing.Ease-in-quart and
	// adw.Easing.Ease-out-quart.
	EaseInOutQuart
	// EaseInQuint: quintic tweening.
	EaseInQuint
	// EaseOutQuint: quintic tweening, inverse of adw.Easing.Ease-in-quint.
	EaseOutQuint
	// EaseInOutQuint: quintic tweening, combining adw.Easing.Ease-in-quint and
	// adw.Easing.Ease-out-quint.
	EaseInOutQuint
	// EaseInSine: sine wave tweening.
	EaseInSine
	// EaseOutSine: sine wave tweening, inverse of adw.Easing.Ease-in-sine.
	EaseOutSine
	// EaseInOutSine: sine wave tweening, combining adw.Easing.Ease-in-sine and
	// adw.Easing.Ease-out-sine.
	EaseInOutSine
	// EaseInExpo: exponential tweening.
	EaseInExpo
	// EaseOutExpo: exponential tweening, inverse of adw.Easing.Ease-in-expo.
	EaseOutExpo
	// EaseInOutExpo: exponential tweening, combining adw.Easing.Ease-in-expo
	// and adw.Easing.Ease-out-expo.
	EaseInOutExpo
	// EaseInCirc: circular tweening.
	EaseInCirc
	// EaseOutCirc: circular tweening, inverse of adw.Easing.Ease-in-circ.
	EaseOutCirc
	// EaseInOutCirc: circular tweening, combining adw.Easing.Ease-in-circ and
	// adw.Easing.Ease-out-circ.
	EaseInOutCirc
	// EaseInElastic: elastic tweening, with offshoot on start.
	EaseInElastic
	// EaseOutElastic: elastic tweening, with offshoot on end, inverse of
	// adw.Easing.Ease-in-elastic.
	EaseOutElastic
	// EaseInOutElastic: elastic tweening, with offshoot on both ends, combining
	// adw.Easing.Ease-in-elastic and adw.Easing.Ease-out-elastic.
	EaseInOutElastic
	// EaseInBack: overshooting cubic tweening, with backtracking on start.
	EaseInBack
	// EaseOutBack: overshooting cubic tweening, with backtracking on end,
	// inverse of adw.Easing.Ease-in-back.
	EaseOutBack
	// EaseInOutBack: overshooting cubic tweening, with backtracking on both
	// ends, combining adw.Easing.Ease-in-back and adw.Easing.Ease-out-back.
	EaseInOutBack
	// EaseInBounce: exponentially decaying parabolic (bounce) tweening,
	// on start.
	EaseInBounce
	// EaseOutBounce: exponentially decaying parabolic (bounce) tweening,
	// with bounce on end, inverse of adw.Easing.Ease-in-bounce.
	EaseOutBounce
	// EaseInOutBounce: exponentially decaying parabolic (bounce) tweening,
	// with bounce on both ends, combining adw.Easing.Ease-in-bounce and
	// adw.Easing.Ease-out-bounce.
	EaseInOutBounce
	// Ease: cubic bezier tweening, with control points in (0.25, 0.1) and
	// (0.25, 1.0).
	//
	// Increases in velocity towards the middle of the animation, slowing back
	// down at the end.
	Ease
	// EaseIn: cubic bezier tweening, with control points in (0.42, 0.0) and
	// (1.0, 1.0).
	//
	// Starts off slowly, with the speed of the animation increasing until
	// complete.
	EaseIn
	// EaseOut: cubic bezier tweening, with control points in (0.0, 0.0) and
	// (0.58, 1.0).
	//
	// Starts quickly, slowing down the animation until complete.
	EaseOut
	// EaseInOut: cubic bezier tweening, with control points in (0.42, 0.0) and
	// (0.58, 1.0).
	//
	// Starts off slowly, speeds up in the middle, and then slows down again.
	EaseInOut
)

func marshalEasing(p uintptr) (interface{}, error) {
	return Easing(coreglib.ValueFromNative(unsafe.Pointer(p)).Enum()), nil
}

// String returns the name in string for Easing.
func (e Easing) String() string {
	switch e {
	case Linear:
		return "Linear"
	case EaseInQuad:
		return "EaseInQuad"
	case EaseOutQuad:
		return "EaseOutQuad"
	case EaseInOutQuad:
		return "EaseInOutQuad"
	case EaseInCubic:
		return "EaseInCubic"
	case EaseOutCubic:
		return "EaseOutCubic"
	case EaseInOutCubic:
		return "EaseInOutCubic"
	case EaseInQuart:
		return "EaseInQuart"
	case EaseOutQuart:
		return "EaseOutQuart"
	case EaseInOutQuart:
		return "EaseInOutQuart"
	case EaseInQuint:
		return "EaseInQuint"
	case EaseOutQuint:
		return "EaseOutQuint"
	case EaseInOutQuint:
		return "EaseInOutQuint"
	case EaseInSine:
		return "EaseInSine"
	case EaseOutSine:
		return "EaseOutSine"
	case EaseInOutSine:
		return "EaseInOutSine"
	case EaseInExpo:
		return "EaseInExpo"
	case EaseOutExpo:
		return "EaseOutExpo"
	case EaseInOutExpo:
		return "EaseInOutExpo"
	case EaseInCirc:
		return "EaseInCirc"
	case EaseOutCirc:
		return "EaseOutCirc"
	case EaseInOutCirc:
		return "EaseInOutCirc"
	case EaseInElastic:
		return "EaseInElastic"
	case EaseOutElastic:
		return "EaseOutElastic"
	case EaseInOutElastic:
		return "EaseInOutElastic"
	case EaseInBack:
		return "EaseInBack"
	case EaseOutBack:
		return "EaseOutBack"
	case EaseInOutBack:
		return "EaseInOutBack"
	case EaseInBounce:
		return "EaseInBounce"
	case EaseOutBounce:
		return "EaseOutBounce"
	case EaseInOutBounce:
		return "EaseInOutBounce"
	case Ease:
		return "Ease"
	case EaseIn:
		return "EaseIn"
	case EaseOut:
		return "EaseOut"
	case EaseInOut:
		return "EaseInOut"
	default:
		return fmt.Sprintf("Easing(%d)", e)
	}
}

// EasingEase computes easing with easing for value.
//
// value should generally be in the [0, 1] range.
//
// The function takes the following parameters:
//
//   - self: easing value.
//   - value to ease.
//
// The function returns the following values:
//
//   - gdouble: easing for value.
func EasingEase(self Easing, value float64) float64 {
	var _arg1 C.AdwEasing // out
	var _arg2 C.double    // out
	var _cret C.double    // in

	_arg1 = C.AdwEasing(self)
	_arg2 = C.double(value)

	_cret = C.adw_easing_ease(_arg1, _arg2)
	runtime.KeepAlive(self)
	runtime.KeepAlive(value)

	var _gdouble float64 // out

	_gdouble = float64(_cret)

	return _gdouble
}
