// Code generated by girgen. DO NOT EDIT.

package adw

// #include <stdlib.h>
// #include <adwaita.h>
import "C"

// ToastClass: instance of this type is always passed by reference.
type ToastClass struct {
	*toastClass
}

// toastClass is the struct that's finalized.
type toastClass struct {
	native *C.AdwToastClass
}
