// Code generated by girgen. DO NOT EDIT.

package adw

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gextras"
	"github.com/diamondburned/gotk4/pkg/gtk/v4"
)

// #include <stdlib.h>
// #include <adwaita.h>
import "C"

// AvatarClass: instance of this type is always passed by reference.
type AvatarClass struct {
	*avatarClass
}

// avatarClass is the struct that's finalized.
type avatarClass struct {
	native *C.AdwAvatarClass
}

func (a *AvatarClass) ParentClass() *gtk.WidgetClass {
	valptr := &a.native.parent_class
	var _v *gtk.WidgetClass // out
	_v = (*gtk.WidgetClass)(gextras.NewStructNative(unsafe.Pointer(valptr)))
	return _v
}
