// Code generated by girgen. DO NOT EDIT.

package adw

// #cgo pkg-config: libadwaita-1
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <adwaita.h>
import "C"

// MAJOR_VERSION: adw major version component (e.g. 1 if ADW_VERSION is 1.2.3).
const MAJOR_VERSION = 1

// MICRO_VERSION: adw micro version component (e.g. 3 if ADW_VERSION is 1.2.3).
const MICRO_VERSION = 0

// MINOR_VERSION: adw minor version component (e.g. 2 if ADW_VERSION is 1.2.3).
const MINOR_VERSION = 0

// VERSION_S: adwaita version, encoded as a string, useful for printing and
// concatenation.
const VERSION_S = "1.0.0.alpha.3"
