// Code generated by girgen. DO NOT EDIT.

package adw

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gextras"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
	"github.com/diamondburned/gotk4/pkg/gtk/v4"
)

// #include <stdlib.h>
// #include <adwaita.h>
// #include <glib-object.h>
import "C"

// GType values.
var (
	GTypeShortcutsDialog = coreglib.Type(C.adw_shortcuts_dialog_get_type())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeShortcutsDialog, F: marshalShortcutsDialog},
	})
}

// ShortcutsDialogOverrides contains methods that are overridable.
type ShortcutsDialogOverrides struct {
}

func defaultShortcutsDialogOverrides(v *ShortcutsDialog) ShortcutsDialogOverrides {
	return ShortcutsDialogOverrides{}
}

// ShortcutsDialog: dialog that displays application's keyboard shortcuts.
//
// <picture> <source srcset="shortcuts-dialog-dark.png"
// media="(prefers-color-scheme: dark)"> <img src="shortcuts-dialog.png"
// alt="shortcuts-dialog"> </picture>
//
// Shortcuts are grouped into sections, represented by shortcutssection objects.
// Each section has one or more items, represented by shortcutsitem objects.
//
// To add a section to the dialog, use shortcutsdialog.Add, or add it as a child
// when using UI files.
//
// Sections without titles can be used to further subdivide each section into
// groups.
//
// Example of an AdwShortcutsDialog UI definition:
//
//	<object class="AdwShortcutsDialog" id="shortcuts_dialog">
//	  <child>
//	    <object class="AdwShortcutsSection">
//	      <property name="title" translatable="yes">General</property>
//	      <child>
//	        <object class="AdwShortcutsItem">
//	          <property name="title" translatable="yes">Open Menu</property>
//	          <property name="accelerator">F10</property>
//	        </object>
//	      </child>
//	      <child>
//	        <object class="AdwShortcutsItem">
//	          <property name="title" translatable="yes">Quit</property>
//	          <property name="action-name">app.quit</property>
//	        </object>
//	      </child>
//	    </object>
//	  </child>
//	  <child>
//	    <object class="AdwShortcutsSection">
//	      <child>
//	        <object class="AdwShortcutsItem">
//	          <property name="title" translatable="yes">Move Tab Left</property>
//	          <property name="accelerator">&lt;Shift&gt;&lt;Ctrl&gt;Page_Up</property>
//	          <property name="direction">ltr</property>
//	        </object>
//	      </child>
//	      <child>
//	        <object class="AdwShortcutsItem">
//	          <property name="title" translatable="yes">Move Tab Right</property>
//	          <property name="accelerator">&lt;Shift&gt;&lt;Ctrl&gt;Page_Down</property>
//	          <property name="direction">ltr</property>
//	        </object>
//	      </child>
//	      <child>
//	        <object class="AdwShortcutsItem">
//	          <property name="title" translatable="yes">Move Tab Right</property>
//	          <property name="accelerator">&lt;Shift&gt;&lt;Ctrl&gt;Page_Up</property>
//	          <property name="direction">rtl</property>
//	        </object>
//	      </child>
//	      <child>
//	        <object class="AdwShortcutsItem">
//	          <property name="title" translatable="yes">Move Tab Left</property>
//	          <property name="accelerator">&lt;Shift&gt;&lt;Ctrl&gt;Page_Down</property>
//	          <property name="direction">rtl</property>
//	        </object>
//	      </child>
//	    </object>
//	  </child>
//	</object>
//
// If the app.quit action has the <kbd>Ctrl</kbd><kbd>Q</kbd> accelerator
// associated with it, the result will look as follows:
//
// <picture> <source srcset="shortcuts-dialog-example-dark.png"
// media="(prefers-color-scheme: dark)"> <img src="shortcuts-dialog-example.png"
// alt="shortcuts-dialog-example"> </picture>
//
// The recommended way to use AdwShortcutsDialog is via application's automatic
// resource loading.
//
// See also: shortcutlabel.
type ShortcutsDialog struct {
	_ [0]func() // equal guard
	Dialog
}

var (
	_ gtk.Widgetter     = (*ShortcutsDialog)(nil)
	_ coreglib.Objector = (*ShortcutsDialog)(nil)
)

func init() {
	coreglib.RegisterClassInfo[*ShortcutsDialog, *ShortcutsDialogClass, ShortcutsDialogOverrides](
		GTypeShortcutsDialog,
		initShortcutsDialogClass,
		wrapShortcutsDialog,
		defaultShortcutsDialogOverrides,
	)
}

func initShortcutsDialogClass(gclass unsafe.Pointer, overrides ShortcutsDialogOverrides, classInitFunc func(*ShortcutsDialogClass)) {
	if classInitFunc != nil {
		class := (*ShortcutsDialogClass)(gextras.NewStructNative(gclass))
		classInitFunc(class)
	}
}

func wrapShortcutsDialog(obj *coreglib.Object) *ShortcutsDialog {
	return &ShortcutsDialog{
		Dialog: Dialog{
			Widget: gtk.Widget{
				InitiallyUnowned: coreglib.InitiallyUnowned{
					Object: obj,
				},
				Object: obj,
				Accessible: gtk.Accessible{
					Object: obj,
				},
				Buildable: gtk.Buildable{
					Object: obj,
				},
				ConstraintTarget: gtk.ConstraintTarget{
					Object: obj,
				},
			},
			Object: obj,
			ShortcutManager: gtk.ShortcutManager{
				Object: obj,
			},
		},
	}
}

func marshalShortcutsDialog(p uintptr) (interface{}, error) {
	return wrapShortcutsDialog(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// NewShortcutsDialog creates a new AdwShortcutsDialog.
//
// The function returns the following values:
//
//   - shortcutsDialog: newly created AdwShortcutsDialog.
func NewShortcutsDialog() *ShortcutsDialog {
	var _cret *C.AdwDialog // in

	_cret = C.adw_shortcuts_dialog_new()

	var _shortcutsDialog *ShortcutsDialog // out

	_shortcutsDialog = wrapShortcutsDialog(coreglib.Take(unsafe.Pointer(_cret)))

	return _shortcutsDialog
}

// Add adds section to self.
//
// The function takes the following parameters:
//
//   - section to add.
func (self *ShortcutsDialog) Add(section *ShortcutsSection) {
	var _arg0 *C.AdwShortcutsDialog  // out
	var _arg1 *C.AdwShortcutsSection // out

	_arg0 = (*C.AdwShortcutsDialog)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	_arg1 = (*C.AdwShortcutsSection)(unsafe.Pointer(coreglib.InternObject(section).Native()))
	C.g_object_ref(C.gpointer(coreglib.InternObject(section).Native()))

	C.adw_shortcuts_dialog_add(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(section)
}
