// Code generated by girgen. DO NOT EDIT.

package adw

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gextras"
)

// #include <stdlib.h>
// #include <adwaita.h>
import "C"

// ShortcutsDialogClass: instance of this type is always passed by reference.
type ShortcutsDialogClass struct {
	*shortcutsDialogClass
}

// shortcutsDialogClass is the struct that's finalized.
type shortcutsDialogClass struct {
	native *C.AdwShortcutsDialogClass
}

func (s *ShortcutsDialogClass) ParentClass() *DialogClass {
	valptr := &s.native.parent_class
	var _v *DialogClass // out
	_v = (*DialogClass)(gextras.NewStructNative(unsafe.Pointer(valptr)))
	return _v
}
