// Code generated by girgen. DO NOT EDIT.

package adw

// #include <stdlib.h>
// #include <adwaita.h>
import "C"

// WindowTitleClass: instance of this type is always passed by reference.
type WindowTitleClass struct {
	*windowTitleClass
}

// windowTitleClass is the struct that's finalized.
type windowTitleClass struct {
	native *C.AdwWindowTitleClass
}
