// Code generated by girgen. DO NOT EDIT.

package adw

import (
	"fmt"
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gextras"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
	"github.com/diamondburned/gotk4/pkg/gdk/v4"
	"github.com/diamondburned/gotk4/pkg/gio/v2"
	"github.com/diamondburned/gotk4/pkg/gtk/v4"
)

// #include <stdlib.h>
// #include <adwaita.h>
// #include <glib-object.h>
// extern void _gotk4_adw1_Sidebar_ConnectSetupMenu(gpointer, AdwSidebarItem*, guintptr);
// extern void _gotk4_adw1_Sidebar_ConnectActivated(gpointer, guint, guintptr);
// extern gboolean _gotk4_adw1_Sidebar_ConnectDrop(gpointer, guint, GValue*, GdkDragAction, guintptr);
// extern GdkDragAction _gotk4_adw1_Sidebar_ConnectDropValueLoaded(gpointer, guint, GValue*, guintptr);
// extern GdkDragAction _gotk4_adw1_Sidebar_ConnectDropEnter(gpointer, guint, guintptr);
import "C"

// GType values.
var (
	GTypeSidebarMode = coreglib.Type(C.adw_sidebar_mode_get_type())
	GTypeSidebar     = coreglib.Type(C.adw_sidebar_get_type())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeSidebarMode, F: marshalSidebarMode},
		coreglib.TypeMarshaler{T: GTypeSidebar, F: marshalSidebar},
	})
}

// SidebarMode determines how an sidebar should look and behave.
//
// See sidebar:mode and viewswitchersidebar:mode.
type SidebarMode C.gint

const (
	// SidebarModeSidebar: sidebar should be displayed as a sidebar.
	SidebarModeSidebar SidebarMode = iota
	// SidebarModePage: sidebar should be displayed as boxed lists page.
	SidebarModePage
)

func marshalSidebarMode(p uintptr) (interface{}, error) {
	return SidebarMode(coreglib.ValueFromNative(unsafe.Pointer(p)).Enum()), nil
}

// String returns the name in string for SidebarMode.
func (s SidebarMode) String() string {
	switch s {
	case SidebarModeSidebar:
		return "Sidebar"
	case SidebarModePage:
		return "Page"
	default:
		return fmt.Sprintf("SidebarMode(%d)", s)
	}
}

// SidebarOverrides contains methods that are overridable.
type SidebarOverrides struct {
}

func defaultSidebarOverrides(v *Sidebar) SidebarOverrides {
	return SidebarOverrides{}
}

// Sidebar: adaptive sidebar widget.
//
// <picture> <source srcset="sidebar-dark.png" media="(prefers-color-scheme:
// dark)"> <img src="sidebar.png" alt="sidebar"> </picture>
//
// AdwSidebar contains sidebarsection objects, which in turn contain sidebaritem
// objects.
//
// To add sections, use sidebar.Append, sidebar.Prepend or sidebar.Insert.
//
// To remove sections, use sidebar.Remove or sidebar.RemoveAll.
//
// To inspect the items, use sidebar.GetItem or sidebar:items.
//
// To inspect sections themselves, use sidebar.GetSection or sidebar:sections.
//
// # Selection and activation
//
// AdwSidebar has zero or one selected items. The index of the item can be
// accessed and changed via sidebar:selected. Set it to gtk.INVALIDLISTPOSITION
// to remove selection.
//
// Selection cannot be permanently disabled.
//
// sidebar:selected-item can be used to access the selected item.
//
// Connect to the sidebar::activated signal to run code when an item has been
// activated. This can be used to toggle the visible pane when used in a split
// view.
//
// See also: viewswitchersidebar.
//
// # Modes
//
// <picture> <source srcset="sidebar-modes-dark.png"
// media="(prefers-color-scheme: dark)"> <img src="sidebar-modes.png"
// alt="sidebar-modes"> </picture>
//
// AdwSidebar is adaptive and can act as either a regular sidebar, or a page of
// boxed lists.
//
// Use the sidebar:mode to determine its look and behavior.
//
// A typical use case involves using AdwSidebar inside the sidebar pane of a
// navigationsplitview, and switching mode to page whenever it's collapsed,
// as follows:
//
//	<object class="AdwWindow">
//	  <property name="default-width">800</property>
//	  <property name="default-height">600</property>
//	  <child>
//	    <object class="AdwBreakpoint">
//	      <condition>max-width: 400sp</condition>
//	      <setter object="split_view" property="collapsed">True</setter>
//	      <setter object="sidebar" property="mode">page</setter>
//	    </object>
//	  </child>
//	  <property name="content">
//	    <object class="AdwNavigationSplitView" id="split_view">
//	      <property name="sidebar">
//	        <object class="AdwNavigationPage">
//	          <property name="title" translatable="yes">Sidebar</property>
//	          <property name="child">
//	            <object class="AdwToolbarView">
//	              <child type="top">
//	                <object class="AdwHeaderBar"/>
//	              </child>
//	              <property name="content">
//	                <object class="AdwSidebar" id="sidebar">
//	                  <!-- Calls adw_navigation_split_view_set_show_content (split_view, TRUE); -->
//	                  <signal name="activated" handler="sidebar_activated_cb"/>
//	                  <!-- ... -->
//	                </object>
//	              </property>
//	            </object>
//	          </property>
//	        </object>
//	      </property>
//	      <property name="content">
//	        <object class="AdwNavigationPage">
//	          <property name="title" translatable="yes">Content</property>
//	          <property name="child">
//	            <!-- ... -->
//	          </property>
//	        </object>
//	      </property>
//	    </object>
//	  </property>
//	</object>
//
// When used with overlaysplitview, the sidebar should stay in sidebar mode,
// as the sidebar pane is still a sidebar when collapsed.
//
// # Search
//
// AdwSidebar supports filtering items via the sidebar:filter property.
//
// Use sidebar:placeholder to provide an empty state widget. It will be shown
// when all items have been filtered out, or the sidebar has no items otherwise.
//
// # Context Menu
//
// To create a context menu for the sidebar items, use the sidebar:menu-model
// property to provide a menu model, and the sidebar::setup-menu signal to set
// up actions for the given item.
//
// To set or override the menu for just one section, use
// sidebarsection:menu-model instead.
//
// # Drag-and-Drop
//
// AdwSidebar items can have a drop target for arbitrary content.
//
// Use sidebar.SetupDropTarget to set it up, specifying the supported content
// types and drag actions, then connect to sidebar::drop to handle drops.
//
// In some cases, it may be necessary to determine the used action based on the
// dragged content, or the hovered item.
//
// To determine it based on the sidebar item, connect to the sidebar::drop-enter
// signal and return the action from its handler.
//
// To determine it based on the content, set sidebar:drop-preload to TRUE,
// then connect to sidebar::drop-value-loaded signal and return the action from
// its handler.
//
// In both cases the action will be passed as a parameter to the sidebar::drop
// signal.
//
// Regardless of whether a drop target was set up, dragging content over sidebar
// items activates them after a timeout. To disable this behavior for specific
// items, set sidebaritem:drag-motion-activate to FALSE on them.
//
// # AdwSidebar as GtkBuildable
//
// AdwSidebar allows adding sections as children.
//
// Example of an AdwSidebar UI definition:
//
//	<object class="AdwSidebar">
//	  <child>
//	    <object class="AdwSidebarSection">
//	      <child>
//	        <object class="AdwSidebarItem">
//	          <property name="title" translatable="yes">Recent</property>
//	          <property name="icon-name">document-open-recent-symbolic</property>
//	        </object>
//	      </child>
//	      <child>
//	        <object class="AdwSidebarItem">
//	          <property name="title" translatable="yes">Starred</property>
//	          <property name="icon-name">starred-symbolic</property>
//	        </object>
//	      </child>
//	    </object>
//	  </child>
//	  <child>
//	    <object class="AdwSidebarSection">
//	      <property name="title" translatable="yes">Places</property>
//	      <child>
//	        <object class="AdwSidebarItem">
//	          <property name="title" translatable="yes">Music</property>
//	          <property name="icon-name">folder-music-symbolic</property>
//	        </object>
//	      </child>
//	      <child>
//	        <object class="AdwSidebarItem">
//	          <property name="title" translatable="yes">Pictures</property>
//	          <property name="icon-name">folder-pictures-symbolic</property>
//	        </object>
//	      </child>
//	      <child>
//	        <object class="AdwSidebarItem">
//	          <property name="title" translatable="yes">Videos</property>
//	          <property name="icon-name">folder-videos-symbolic</property>
//	        </object>
//	      </child>
//	    </object>
//	  </child>
//	  <child>
//	    <object class="AdwSidebarSection">
//	      <child>
//	        <object class="AdwSidebarItem">
//	          <property name="title" translatable="yes">Trash</property>
//	          <property name="icon-name">user-trash-symbolic</property>
//	        </object>
//	      </child>
//	    </object>
//	  </child>
//	</object>
//
// # CSS nodes
//
// AdwSidebar has a main CSS node with the name sidebar.
//
// Internally, it's using a gtk.ListBox with the .navigation-sidebar
// (style-classes.html#sidebars) style class in sidebar mode, or an
// preferencespage in page mode.
//
// # Accessibility
//
// AdwSidebar uses the gtk.AccessibleRole.Generic role.
type Sidebar struct {
	_ [0]func() // equal guard
	gtk.Widget
}

var (
	_ gtk.Widgetter = (*Sidebar)(nil)
)

func init() {
	coreglib.RegisterClassInfo[*Sidebar, *SidebarClass, SidebarOverrides](
		GTypeSidebar,
		initSidebarClass,
		wrapSidebar,
		defaultSidebarOverrides,
	)
}

func initSidebarClass(gclass unsafe.Pointer, overrides SidebarOverrides, classInitFunc func(*SidebarClass)) {
	if classInitFunc != nil {
		class := (*SidebarClass)(gextras.NewStructNative(gclass))
		classInitFunc(class)
	}
}

func wrapSidebar(obj *coreglib.Object) *Sidebar {
	return &Sidebar{
		Widget: gtk.Widget{
			InitiallyUnowned: coreglib.InitiallyUnowned{
				Object: obj,
			},
			Object: obj,
			Accessible: gtk.Accessible{
				Object: obj,
			},
			Buildable: gtk.Buildable{
				Object: obj,
			},
			ConstraintTarget: gtk.ConstraintTarget{
				Object: obj,
			},
		},
	}
}

func marshalSidebar(p uintptr) (interface{}, error) {
	return wrapSidebar(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// ConnectActivated is emitted when an item at index has been activated.
func (self *Sidebar) ConnectActivated(f func(index uint)) coreglib.SignalHandle {
	return coreglib.ConnectGeneratedClosure(self, "activated", false, unsafe.Pointer(C._gotk4_adw1_Sidebar_ConnectActivated), f)
}

// ConnectDrop is emitted when content is dropped onto the item at index.
//
// The content must be of one of the types set up via sidebar.SetupDropTarget.
//
// See gtk.DropTarget::drop.
func (self *Sidebar) ConnectDrop(f func(index uint, value *coreglib.Value, preferredAction gdk.DragAction) (ok bool)) coreglib.SignalHandle {
	return coreglib.ConnectGeneratedClosure(self, "drop", false, unsafe.Pointer(C._gotk4_adw1_Sidebar_ConnectDrop), f)
}

// ConnectDropEnter is emitted when the pointer enters the item at index.
//
// Applications can use this to set their default drop action even when
// sidebar:drop-preload is set to FALSE.
//
// See gtk.DropTarget::enter.
func (self *Sidebar) ConnectDropEnter(f func(index uint) (dragAction gdk.DragAction)) coreglib.SignalHandle {
	return coreglib.ConnectGeneratedClosure(self, "drop-enter", false, unsafe.Pointer(C._gotk4_adw1_Sidebar_ConnectDropEnter), f)
}

// ConnectDropValueLoaded is emitted when the dropped content is preloaded for
// the item at index.
//
// In order for data to be preloaded, sidebar:drop-preload must be set to TRUE.
//
// The content must be of one of the types set up via sidebar.SetupDropTarget.
//
// See gtk.DropTarget:value.
func (self *Sidebar) ConnectDropValueLoaded(f func(index uint, value *coreglib.Value) (dragAction gdk.DragAction)) coreglib.SignalHandle {
	return coreglib.ConnectGeneratedClosure(self, "drop-value-loaded", false, unsafe.Pointer(C._gotk4_adw1_Sidebar_ConnectDropValueLoaded), f)
}

// ConnectSetupMenu is emitted when a context menu is opened or closed for item.
//
// If the menu has been closed, item will be set to NULL.
//
// It can be used to set up menu actions before showing the menu, for example
// disable actions not applicable to item.
func (self *Sidebar) ConnectSetupMenu(f func(item *SidebarItem)) coreglib.SignalHandle {
	return coreglib.ConnectGeneratedClosure(self, "setup-menu", false, unsafe.Pointer(C._gotk4_adw1_Sidebar_ConnectSetupMenu), f)
}

// NewSidebar creates a new AdwSidebar.
//
// The function returns the following values:
//
//   - sidebar: newly created AdwSidebar.
func NewSidebar() *Sidebar {
	var _cret *C.GtkWidget // in

	_cret = C.adw_sidebar_new()

	var _sidebar *Sidebar // out

	_sidebar = wrapSidebar(coreglib.Take(unsafe.Pointer(_cret)))

	return _sidebar
}

// Append appends section to self.
//
// The function takes the following parameters:
//
//   - section to append.
func (self *Sidebar) Append(section *SidebarSection) {
	var _arg0 *C.AdwSidebar        // out
	var _arg1 *C.AdwSidebarSection // out

	_arg0 = (*C.AdwSidebar)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	_arg1 = (*C.AdwSidebarSection)(unsafe.Pointer(coreglib.InternObject(section).Native()))
	C.g_object_ref(C.gpointer(coreglib.InternObject(section).Native()))

	C.adw_sidebar_append(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(section)
}

// DropPreload gets whether drop data should be preloaded on hover.
//
// The function returns the following values:
//
//   - ok: whether drop data should be preloaded on hover.
func (self *Sidebar) DropPreload() bool {
	var _arg0 *C.AdwSidebar // out
	var _cret C.gboolean    // in

	_arg0 = (*C.AdwSidebar)(unsafe.Pointer(coreglib.InternObject(self).Native()))

	_cret = C.adw_sidebar_get_drop_preload(_arg0)
	runtime.KeepAlive(self)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// Filter gets the item filter for self.
//
// The function returns the following values:
//
//   - filter (optional): item filter.
func (self *Sidebar) Filter() *gtk.Filter {
	var _arg0 *C.AdwSidebar // out
	var _cret *C.GtkFilter  // in

	_arg0 = (*C.AdwSidebar)(unsafe.Pointer(coreglib.InternObject(self).Native()))

	_cret = C.adw_sidebar_get_filter(_arg0)
	runtime.KeepAlive(self)

	var _filter *gtk.Filter // out

	if _cret != nil {
		{
			obj := coreglib.Take(unsafe.Pointer(_cret))
			_filter = &gtk.Filter{
				Object: obj,
			}
		}
	}

	return _filter
}

// Item gets the item at index within self.
//
// The index starts from 0 at the top of the sidebar, and is same as the one
// returned by sidebaritem.GetIndex.
//
// Can return NULL if index is larger or equal to the number of items.
//
// The function takes the following parameters:
//
//   - index of the item.
//
// The function returns the following values:
//
//   - sidebarItem (optional): item at index.
func (self *Sidebar) Item(index uint) *SidebarItem {
	var _arg0 *C.AdwSidebar     // out
	var _arg1 C.guint           // out
	var _cret *C.AdwSidebarItem // in

	_arg0 = (*C.AdwSidebar)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	_arg1 = C.guint(index)

	_cret = C.adw_sidebar_get_item(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(index)

	var _sidebarItem *SidebarItem // out

	if _cret != nil {
		_sidebarItem = wrapSidebarItem(coreglib.Take(unsafe.Pointer(_cret)))
	}

	return _sidebarItem
}

// Items gets a list model with self's items.
//
// This can be used to keep an up-to-date view.
//
// The model implements gtk.SectionModel and creates sections corresponding to
// the sidebar's sections.
//
// The model also implements gtk.SelectionModel and can be used to track and
// change the selection.
//
// To only track sections, use sidebar:sections instead.
//
// The function returns the following values:
//
//   - selectionModel: model containing the items.
func (self *Sidebar) Items() *gtk.SelectionModel {
	var _arg0 *C.AdwSidebar        // out
	var _cret *C.GtkSelectionModel // in

	_arg0 = (*C.AdwSidebar)(unsafe.Pointer(coreglib.InternObject(self).Native()))

	_cret = C.adw_sidebar_get_items(_arg0)
	runtime.KeepAlive(self)

	var _selectionModel *gtk.SelectionModel // out

	{
		obj := coreglib.AssumeOwnership(unsafe.Pointer(_cret))
		_selectionModel = &gtk.SelectionModel{
			ListModel: gio.ListModel{
				Object: obj,
			},
		}
	}

	return _selectionModel
}

// MenuModel gets the context menu model for self's items.
//
// The function returns the following values:
//
//   - menuModel (optional): context menu model.
func (self *Sidebar) MenuModel() gio.MenuModeller {
	var _arg0 *C.AdwSidebar // out
	var _cret *C.GMenuModel // in

	_arg0 = (*C.AdwSidebar)(unsafe.Pointer(coreglib.InternObject(self).Native()))

	_cret = C.adw_sidebar_get_menu_model(_arg0)
	runtime.KeepAlive(self)

	var _menuModel gio.MenuModeller // out

	if _cret != nil {
		{
			objptr := unsafe.Pointer(_cret)

			object := coreglib.Take(objptr)
			casted := object.WalkCast(func(obj coreglib.Objector) bool {
				_, ok := obj.(gio.MenuModeller)
				return ok
			})
			rv, ok := casted.(gio.MenuModeller)
			if !ok {
				panic("no marshaler for " + object.TypeFromInstance().String() + " matching gio.MenuModeller")
			}
			_menuModel = rv
		}
	}

	return _menuModel
}

// Mode gets self's look and behavior.
//
// The function returns the following values:
//
//   - sidebarMode: current mode.
func (self *Sidebar) Mode() SidebarMode {
	var _arg0 *C.AdwSidebar    // out
	var _cret C.AdwSidebarMode // in

	_arg0 = (*C.AdwSidebar)(unsafe.Pointer(coreglib.InternObject(self).Native()))

	_cret = C.adw_sidebar_get_mode(_arg0)
	runtime.KeepAlive(self)

	var _sidebarMode SidebarMode // out

	_sidebarMode = SidebarMode(_cret)

	return _sidebarMode
}

// Placeholder gets the placeholder widget for self.
//
// The function returns the following values:
//
//   - widget (optional): placeholder widget.
func (self *Sidebar) Placeholder() gtk.Widgetter {
	var _arg0 *C.AdwSidebar // out
	var _cret *C.GtkWidget  // in

	_arg0 = (*C.AdwSidebar)(unsafe.Pointer(coreglib.InternObject(self).Native()))

	_cret = C.adw_sidebar_get_placeholder(_arg0)
	runtime.KeepAlive(self)

	var _widget gtk.Widgetter // out

	if _cret != nil {
		{
			objptr := unsafe.Pointer(_cret)

			object := coreglib.Take(objptr)
			casted := object.WalkCast(func(obj coreglib.Objector) bool {
				_, ok := obj.(gtk.Widgetter)
				return ok
			})
			rv, ok := casted.(gtk.Widgetter)
			if !ok {
				panic("no marshaler for " + object.TypeFromInstance().String() + " matching gtk.Widgetter")
			}
			_widget = rv
		}
	}

	return _widget
}

// Section gets the section at index within self.
//
// Can return NULL if index is larger or equal to the number of sections.
//
// The function takes the following parameters:
//
//   - index of the section.
//
// The function returns the following values:
//
//   - sidebarSection (optional): section at index.
func (self *Sidebar) Section(index uint) *SidebarSection {
	var _arg0 *C.AdwSidebar        // out
	var _arg1 C.guint              // out
	var _cret *C.AdwSidebarSection // in

	_arg0 = (*C.AdwSidebar)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	_arg1 = C.guint(index)

	_cret = C.adw_sidebar_get_section(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(index)

	var _sidebarSection *SidebarSection // out

	if _cret != nil {
		_sidebarSection = wrapSidebarSection(coreglib.Take(unsafe.Pointer(_cret)))
	}

	return _sidebarSection
}

// Sections gets a list model with self's sections.
//
// This can be used to keep an up-to-date view.
//
// To track items, use sidebar:items instead.
//
// The function returns the following values:
//
//   - listModel: model containing the sections.
func (self *Sidebar) Sections() *gio.ListModel {
	var _arg0 *C.AdwSidebar // out
	var _cret *C.GListModel // in

	_arg0 = (*C.AdwSidebar)(unsafe.Pointer(coreglib.InternObject(self).Native()))

	_cret = C.adw_sidebar_get_sections(_arg0)
	runtime.KeepAlive(self)

	var _listModel *gio.ListModel // out

	{
		obj := coreglib.AssumeOwnership(unsafe.Pointer(_cret))
		_listModel = &gio.ListModel{
			Object: obj,
		}
	}

	return _listModel
}

// Selected gets the index of the currently selected item.
//
// See also: sidebar.GetSelectedItem.
//
// The function returns the following values:
//
//   - guint: index of the currently selected item.
func (self *Sidebar) Selected() uint {
	var _arg0 *C.AdwSidebar // out
	var _cret C.guint       // in

	_arg0 = (*C.AdwSidebar)(unsafe.Pointer(coreglib.InternObject(self).Native()))

	_cret = C.adw_sidebar_get_selected(_arg0)
	runtime.KeepAlive(self)

	var _guint uint // out

	_guint = uint(_cret)

	return _guint
}

// SelectedItem gets the currently selected item.
//
// This is a convenience method, equivalent to calling sidebar.GetItem with
// sidebar:selected provided as the index.
//
// To change selection, use sidebar.SetSelected.
//
// The function returns the following values:
//
//   - sidebarItem (optional): selected item.
func (self *Sidebar) SelectedItem() *SidebarItem {
	var _arg0 *C.AdwSidebar     // out
	var _cret *C.AdwSidebarItem // in

	_arg0 = (*C.AdwSidebar)(unsafe.Pointer(coreglib.InternObject(self).Native()))

	_cret = C.adw_sidebar_get_selected_item(_arg0)
	runtime.KeepAlive(self)

	var _sidebarItem *SidebarItem // out

	if _cret != nil {
		_sidebarItem = wrapSidebarItem(coreglib.Take(unsafe.Pointer(_cret)))
	}

	return _sidebarItem
}

// Insert inserts section at position to self.
//
// If position is -1, or larger than the total number of sections in self,
// the section will be appended to the end.
//
// The function takes the following parameters:
//
//   - section to insert.
//   - position to insert section at.
func (self *Sidebar) Insert(section *SidebarSection, position int) {
	var _arg0 *C.AdwSidebar        // out
	var _arg1 *C.AdwSidebarSection // out
	var _arg2 C.int                // out

	_arg0 = (*C.AdwSidebar)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	_arg1 = (*C.AdwSidebarSection)(unsafe.Pointer(coreglib.InternObject(section).Native()))
	C.g_object_ref(C.gpointer(coreglib.InternObject(section).Native()))
	_arg2 = C.int(position)

	C.adw_sidebar_insert(_arg0, _arg1, _arg2)
	runtime.KeepAlive(self)
	runtime.KeepAlive(section)
	runtime.KeepAlive(position)
}

// Prepend prepends section to self.
//
// The function takes the following parameters:
//
//   - section to prepend.
func (self *Sidebar) Prepend(section *SidebarSection) {
	var _arg0 *C.AdwSidebar        // out
	var _arg1 *C.AdwSidebarSection // out

	_arg0 = (*C.AdwSidebar)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	_arg1 = (*C.AdwSidebarSection)(unsafe.Pointer(coreglib.InternObject(section).Native()))
	C.g_object_ref(C.gpointer(coreglib.InternObject(section).Native()))

	C.adw_sidebar_prepend(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(section)
}

// Remove removes section from self.
//
// The function takes the following parameters:
//
//   - section to remove.
func (self *Sidebar) Remove(section *SidebarSection) {
	var _arg0 *C.AdwSidebar        // out
	var _arg1 *C.AdwSidebarSection // out

	_arg0 = (*C.AdwSidebar)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	_arg1 = (*C.AdwSidebarSection)(unsafe.Pointer(coreglib.InternObject(section).Native()))

	C.adw_sidebar_remove(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(section)
}

// RemoveAll removes all sections from self.
func (self *Sidebar) RemoveAll() {
	var _arg0 *C.AdwSidebar // out

	_arg0 = (*C.AdwSidebar)(unsafe.Pointer(coreglib.InternObject(self).Native()))

	C.adw_sidebar_remove_all(_arg0)
	runtime.KeepAlive(self)
}

// SetDropPreload sets whether drop data should be preloaded on hover.
//
// See gtk.DropTarget:preload.
//
// The function takes the following parameters:
//
//   - preload: whether to preload drop data.
func (self *Sidebar) SetDropPreload(preload bool) {
	var _arg0 *C.AdwSidebar // out
	var _arg1 C.gboolean    // out

	_arg0 = (*C.AdwSidebar)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	if preload {
		_arg1 = C.TRUE
	}

	C.adw_sidebar_set_drop_preload(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(preload)
}

// SetFilter sets the item filter for self.
//
// Can be used to implement search within the sidebar.
//
// Use sidebar:placeholder to provide an empty state.
//
// The function takes the following parameters:
//
//   - filter (optional): item filter.
func (self *Sidebar) SetFilter(filter *gtk.Filter) {
	var _arg0 *C.AdwSidebar // out
	var _arg1 *C.GtkFilter  // out

	_arg0 = (*C.AdwSidebar)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	if filter != nil {
		_arg1 = (*C.GtkFilter)(unsafe.Pointer(coreglib.InternObject(filter).Native()))
	}

	C.adw_sidebar_set_filter(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(filter)
}

// SetMenuModel sets the context menu model for self's items.
//
// When a context menu is shown for an item, it will be constructed from the
// provided menu model. Use the sidebar::setup-menu signal to set up the menu
// actions for the particular item.
//
// sidebar:menu-model will be preferred over this model if set.
//
// The function takes the following parameters:
//
//   - menuModel (optional): menu model.
func (self *Sidebar) SetMenuModel(menuModel gio.MenuModeller) {
	var _arg0 *C.AdwSidebar // out
	var _arg1 *C.GMenuModel // out

	_arg0 = (*C.AdwSidebar)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	if menuModel != nil {
		_arg1 = (*C.GMenuModel)(unsafe.Pointer(coreglib.InternObject(menuModel).Native()))
	}

	C.adw_sidebar_set_menu_model(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(menuModel)
}

// SetMode sets self's look and behavior.
//
// <picture> <source srcset="sidebar-modes-dark.png"
// media="(prefers-color-scheme: dark)"> <img src="sidebar-modes.png"
// alt="sidebar-modes"> </picture>
//
// If set to adw.SidebarMode.Sidebar, behaves like a sidebar: with a sidebar
// style and a persistent selection.
//
// If set to adw.SidebarMode.Page, behaves like a page of boxed lists. In this
// mode, the selection is invisible and only tracked to determine the initially
// selected item once switched back to sidebar mode.
//
// The page mode is intended to be used with navigationsplitview when collapsed,
// as the sidebar pane becomes a page there.
//
// When used with overlaysplitview, the sidebar should stay in sidebar mode,
// as the sidebar pane is still a sidebar when collapsed.
//
// The function takes the following parameters:
//
//   - mode: new mode.
func (self *Sidebar) SetMode(mode SidebarMode) {
	var _arg0 *C.AdwSidebar    // out
	var _arg1 C.AdwSidebarMode // out

	_arg0 = (*C.AdwSidebar)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	_arg1 = C.AdwSidebarMode(mode)

	C.adw_sidebar_set_mode(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(mode)
}

// SetPlaceholder sets the placeholder widget for self.
//
// This widget will be shown if self has no items, or all of its items have been
// filtered out by sidebar:filter.
//
// The function takes the following parameters:
//
//   - placeholder (optional) widget.
func (self *Sidebar) SetPlaceholder(placeholder gtk.Widgetter) {
	var _arg0 *C.AdwSidebar // out
	var _arg1 *C.GtkWidget  // out

	_arg0 = (*C.AdwSidebar)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	if placeholder != nil {
		_arg1 = (*C.GtkWidget)(unsafe.Pointer(coreglib.InternObject(placeholder).Native()))
	}

	C.adw_sidebar_set_placeholder(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(placeholder)
}

// SetSelected selects the item at selected.
//
// If set to gtk.INVALIDLISTPOSITION, no item is selected.
//
// If sidebar:mode is set to adw.SidebarMode.Page, the selection is invisible,
// but still tracked, indicating which item will be selected once the mode is
// changed to adw.SidebarMode.Sidebar.
//
// See also: sidebar:selected-item.
//
// The function takes the following parameters:
//
//   - selected: index of the newly selected item.
func (self *Sidebar) SetSelected(selected uint) {
	var _arg0 *C.AdwSidebar // out
	var _arg1 C.guint       // out

	_arg0 = (*C.AdwSidebar)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	_arg1 = C.guint(selected)

	C.adw_sidebar_set_selected(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(selected)
}

// SetupDropTarget sets up a drop target on the items.
//
// This allows to drag arbitrary content onto items.
//
// The sidebar::drop signal can be used to handle the drop.
//
// The function takes the following parameters:
//
//   - actions: supported actions.
//   - types (optional): all supported GTypes that can be dropped.
func (self *Sidebar) SetupDropTarget(actions gdk.DragAction, types []coreglib.Type) {
	var _arg0 *C.AdwSidebar   // out
	var _arg1 C.GdkDragAction // out
	var _arg2 *C.GType        // out
	var _arg3 C.gsize

	_arg0 = (*C.AdwSidebar)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	_arg1 = C.GdkDragAction(actions)
	_arg3 = (C.gsize)(len(types))
	_arg2 = (*C.GType)(C.calloc(C.size_t(len(types)), C.size_t(C.sizeof_GType)))
	defer C.free(unsafe.Pointer(_arg2))
	{
		out := unsafe.Slice((*C.GType)(_arg2), len(types))
		for i := range types {
			out[i] = C.GType(types[i])
		}
	}

	C.adw_sidebar_setup_drop_target(_arg0, _arg1, _arg2, _arg3)
	runtime.KeepAlive(self)
	runtime.KeepAlive(actions)
	runtime.KeepAlive(types)
}
