// Code generated by girgen. DO NOT EDIT.

package adw

// #cgo pkg-config: libadwaita-1
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <adwaita.h>
import "C"

// Init: call this function just after initializing GTK, if you are using
// Application it means it must be called when the #GApplication::startup signal
// is emitted. If libadwaita has already been initialized, the function will
// simply return.
//
// This makes sure translations, types, themes, and icons for the Adwaita
// library are set up properly.
func Init() {
	C.adw_init()
}
