// Code generated by girgen. DO NOT EDIT.

package adw

// #include <stdlib.h>
// #include <adwaita.h>
import "C"

// MAJOR_VERSION: adwaita major version component (e.g. 1 if the version is
// 1.2.3).
const MAJOR_VERSION = 1

// MICRO_VERSION: adwaita micro version component (e.g. 3 if the version is
// 1.2.3).
const MICRO_VERSION = 2

// MINOR_VERSION: adwaita minor version component (e.g. 2 if the version is
// 1.2.3).
const MINOR_VERSION = 7

// VERSION_S: adwaita version, encoded as a string, useful for printing and
// concatenation.
const VERSION_S = "1.7.2"

// GetMajorVersion returns the major version number of the Adwaita library.
//
// For example, in libadwaita version 1.2.3 this is 1.
//
// This function is in the library, so it represents the libadwaita library
// your code is running against. Contrast with the major_version constant, which
// represents the major version of the libadwaita headers you have included when
// compiling your code.
//
// The function returns the following values:
//
//   - guint: major version number of the Adwaita library.
func GetMajorVersion() uint {
	var _cret C.guint // in

	_cret = C.adw_get_major_version()

	var _guint uint // out

	_guint = uint(_cret)

	return _guint
}

// GetMicroVersion returns the micro version number of the Adwaita library.
//
// For example, in libadwaita version 1.2.3 this is 3.
//
// This function is in the library, so it represents the libadwaita library
// your code is running against. Contrast with the major_version constant, which
// represents the micro version of the libadwaita headers you have included when
// compiling your code.
//
// The function returns the following values:
//
//   - guint: micro version number of the Adwaita library.
func GetMicroVersion() uint {
	var _cret C.guint // in

	_cret = C.adw_get_micro_version()

	var _guint uint // out

	_guint = uint(_cret)

	return _guint
}

// GetMinorVersion returns the minor version number of the Adwaita library.
//
// For example, in libadwaita version 1.2.3 this is 2.
//
// This function is in the library, so it represents the libadwaita library
// your code is running against. Contrast with the major_version constant, which
// represents the minor version of the libadwaita headers you have included when
// compiling your code.
//
// The function returns the following values:
//
//   - guint: minor version number of the Adwaita library.
func GetMinorVersion() uint {
	var _cret C.guint // in

	_cret = C.adw_get_minor_version()

	var _guint uint // out

	_guint = uint(_cret)

	return _guint
}
