// Code generated by girgen. DO NOT EDIT.

package adw

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gbox"
	"github.com/diamondburned/gotk4/pkg/core/gextras"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
	"github.com/diamondburned/gotk4/pkg/gio/v2"
	"github.com/diamondburned/gotk4/pkg/gtk/v4"
)

// #include <stdlib.h>
// #include <adwaita.h>
// #include <glib-object.h>
// extern void callbackDelete(gpointer);
// extern AdwSidebarItem* _gotk4_adw1_SidebarSectionCreateItemFunc(gpointer, gpointer);
import "C"

// GType values.
var (
	GTypeSidebarSection = coreglib.Type(C.adw_sidebar_section_get_type())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeSidebarSection, F: marshalSidebarSection},
	})
}

// SidebarSectionCreateItemFunc: called for sidebars that are bound to a
// gio.ListModel with sidebarsection.BindModel for each item that gets added to
// the model.
type SidebarSectionCreateItemFunc func(item *coreglib.Object) (sidebarItem *SidebarItem)

// SidebarSectionOverrides contains methods that are overridable.
type SidebarSectionOverrides struct {
}

func defaultSidebarSectionOverrides(v *SidebarSection) SidebarSectionOverrides {
	return SidebarSectionOverrides{}
}

// SidebarSection: section within sidebar.
//
// AdwSidebarSection contains sidebaritem objects.
//
// Section can optionally have a title, set with the sidebarsection:title
// property. If a title is not set, the section will have a separator in front
// of it, or just spacing in the adw.SidebarMode.Page mode.
//
// To add items, use sidebarsection.Append, sidebarsection.Prepend or
// sidebarsection.Insert.
//
// To remove items, use sidebarsection.Remove or sidebarsection.RemoveAll.
//
// To inspect the items, use sidebarsection.GetItem or sidebarsection:items.
//
// To get the sidebar the section is in, usesidebarsection:sidebar.
//
// # Binding models
//
// AdwSidebarSection can show items from a provided gio.ListModel, using
// sidebarsection.BindModel. It works the same way as gtk.ListBox.BindModel(),
// except the provided function creates an sidebaritem rather than a
// gtk.ListBoxRow.
//
// While a model is bound, adding or removing items manually is not allowed.
// Inspecting them is still allowed, but discouraged.
//
// # AdwSidebarSection as GtkBuildable
//
// AdwSidebarSection allows adding items as children.
//
// Example of an AdwSidebarSection UI definition:
//
//	<object class="AdwSidebarSection">
//	  <property name="title" translatable="yes">Places</property>
//	  <child>
//	    <object class="AdwSidebarItem">
//	      <property name="title" translatable="yes">Music</property>
//	      <property name="icon-name">folder-music-symbolic</property>
//	    </object>
//	  </child>
//	  <child>
//	    <object class="AdwSidebarItem">
//	      <property name="title" translatable="yes">Pictures</property>
//	      <property name="icon-name">folder-pictures-symbolic</property>
//	    </object>
//	  </child>
//	  <child>
//	    <object class="AdwSidebarItem">
//	      <property name="title" translatable="yes">Videos</property>
//	      <property name="icon-name">folder-videos-symbolic</property>
//	    </object>
//	  </child>
//	</object>
//
// Result:
//
// <picture> <source srcset="sidebar-section-dark.png"
// media="(prefers-color-scheme: dark)"> <img src="sidebar-section.png"
// alt="sidebar-section"> </picture>.
type SidebarSection struct {
	_ [0]func() // equal guard
	*coreglib.Object

	gtk.Buildable
}

var (
	_ coreglib.Objector = (*SidebarSection)(nil)
)

func init() {
	coreglib.RegisterClassInfo[*SidebarSection, *SidebarSectionClass, SidebarSectionOverrides](
		GTypeSidebarSection,
		initSidebarSectionClass,
		wrapSidebarSection,
		defaultSidebarSectionOverrides,
	)
}

func initSidebarSectionClass(gclass unsafe.Pointer, overrides SidebarSectionOverrides, classInitFunc func(*SidebarSectionClass)) {
	if classInitFunc != nil {
		class := (*SidebarSectionClass)(gextras.NewStructNative(gclass))
		classInitFunc(class)
	}
}

func wrapSidebarSection(obj *coreglib.Object) *SidebarSection {
	return &SidebarSection{
		Object: obj,
		Buildable: gtk.Buildable{
			Object: obj,
		},
	}
}

func marshalSidebarSection(p uintptr) (interface{}, error) {
	return wrapSidebarSection(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// NewSidebarSection creates a new AdwSidebarSection.
//
// The function returns the following values:
//
//   - sidebarSection: newly created AdwSidebarSection.
func NewSidebarSection() *SidebarSection {
	var _cret *C.AdwSidebarSection // in

	_cret = C.adw_sidebar_section_new()

	var _sidebarSection *SidebarSection // out

	_sidebarSection = wrapSidebarSection(coreglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _sidebarSection
}

// Append appends item to self.
//
// Cannot be used while a model is bound via sidebarsection.BindModel.
//
// The function takes the following parameters:
//
//   - item to append.
func (self *SidebarSection) Append(item *SidebarItem) {
	var _arg0 *C.AdwSidebarSection // out
	var _arg1 *C.AdwSidebarItem    // out

	_arg0 = (*C.AdwSidebarSection)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	_arg1 = (*C.AdwSidebarItem)(unsafe.Pointer(coreglib.InternObject(item).Native()))
	C.g_object_ref(C.gpointer(coreglib.InternObject(item).Native()))

	C.adw_sidebar_section_append(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(item)
}

// BindModel binds model to self.
//
// If self was already bound to a model, that previous binding is destroyed.
//
// The contents of self are cleared and then filled with items that represent
// items from model. self is updated whenever model changes.
//
// If model is NULL, self is left empty.
//
// Calling sidebarsection.Prepend, sidebarsection.Insert, sidebarsection.Append,
// sidebarsection.Remove or sidebarsection.RemoveAll while a model is bound is
// not allowed.
//
// Accessing items and modifying them is allowed, but the changes will be erased
// whenever that part of the model changes, so it's not recommended.
//
// The function takes the following parameters:
//
//   - model (optional) to be bound.
//   - createItemFunc (optional): a function that creates sidebaritem for model
//     items, or NULL in case model is also NULL.
func (self *SidebarSection) BindModel(model gio.ListModeller, createItemFunc SidebarSectionCreateItemFunc) {
	var _arg0 *C.AdwSidebarSection              // out
	var _arg1 *C.GListModel                     // out
	var _arg2 C.AdwSidebarSectionCreateItemFunc // out
	var _arg3 C.gpointer
	var _arg4 C.GDestroyNotify

	_arg0 = (*C.AdwSidebarSection)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	if model != nil {
		_arg1 = (*C.GListModel)(unsafe.Pointer(coreglib.InternObject(model).Native()))
	}
	if createItemFunc != nil {
		_arg2 = (*[0]byte)(C._gotk4_adw1_SidebarSectionCreateItemFunc)
		_arg3 = C.gpointer(gbox.Assign(createItemFunc))
		_arg4 = (C.GDestroyNotify)((*[0]byte)(C.callbackDelete))
	}

	C.adw_sidebar_section_bind_model(_arg0, _arg1, _arg2, _arg3, _arg4)
	runtime.KeepAlive(self)
	runtime.KeepAlive(model)
	runtime.KeepAlive(createItemFunc)
}

// Item gets the item at index within self.
//
// The index starts from 0 at the top of the section, and is same as the one
// returned by sidebaritem.GetSectionIndex.
//
// Can return NULL if index is larger or equal to the number of items.
//
// The function takes the following parameters:
//
//   - index of the item.
//
// The function returns the following values:
//
//   - sidebarItem (optional): item at index.
func (self *SidebarSection) Item(index uint) *SidebarItem {
	var _arg0 *C.AdwSidebarSection // out
	var _arg1 C.guint              // out
	var _cret *C.AdwSidebarItem    // in

	_arg0 = (*C.AdwSidebarSection)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	_arg1 = C.guint(index)

	_cret = C.adw_sidebar_section_get_item(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(index)

	var _sidebarItem *SidebarItem // out

	if _cret != nil {
		_sidebarItem = wrapSidebarItem(coreglib.Take(unsafe.Pointer(_cret)))
	}

	return _sidebarItem
}

// Items gets a list model with self's items.
//
// This can be used to keep an up-to-date view.
//
// The function returns the following values:
//
//   - listModel: model containing the items.
func (self *SidebarSection) Items() *gio.ListModel {
	var _arg0 *C.AdwSidebarSection // out
	var _cret *C.GListModel        // in

	_arg0 = (*C.AdwSidebarSection)(unsafe.Pointer(coreglib.InternObject(self).Native()))

	_cret = C.adw_sidebar_section_get_items(_arg0)
	runtime.KeepAlive(self)

	var _listModel *gio.ListModel // out

	{
		obj := coreglib.AssumeOwnership(unsafe.Pointer(_cret))
		_listModel = &gio.ListModel{
			Object: obj,
		}
	}

	return _listModel
}

// MenuModel gets the context menu model for self's items.
//
// The function returns the following values:
//
//   - menuModel (optional): context menu model.
func (self *SidebarSection) MenuModel() gio.MenuModeller {
	var _arg0 *C.AdwSidebarSection // out
	var _cret *C.GMenuModel        // in

	_arg0 = (*C.AdwSidebarSection)(unsafe.Pointer(coreglib.InternObject(self).Native()))

	_cret = C.adw_sidebar_section_get_menu_model(_arg0)
	runtime.KeepAlive(self)

	var _menuModel gio.MenuModeller // out

	if _cret != nil {
		{
			objptr := unsafe.Pointer(_cret)

			object := coreglib.Take(objptr)
			casted := object.WalkCast(func(obj coreglib.Objector) bool {
				_, ok := obj.(gio.MenuModeller)
				return ok
			})
			rv, ok := casted.(gio.MenuModeller)
			if !ok {
				panic("no marshaler for " + object.TypeFromInstance().String() + " matching gio.MenuModeller")
			}
			_menuModel = rv
		}
	}

	return _menuModel
}

// Sidebar gets the sidebar self is in.
//
// The function returns the following values:
//
//   - sidebar (optional) of self.
func (self *SidebarSection) Sidebar() *Sidebar {
	var _arg0 *C.AdwSidebarSection // out
	var _cret *C.AdwSidebar        // in

	_arg0 = (*C.AdwSidebarSection)(unsafe.Pointer(coreglib.InternObject(self).Native()))

	_cret = C.adw_sidebar_section_get_sidebar(_arg0)
	runtime.KeepAlive(self)

	var _sidebar *Sidebar // out

	if _cret != nil {
		_sidebar = wrapSidebar(coreglib.Take(unsafe.Pointer(_cret)))
	}

	return _sidebar
}

// Title gets the title of self.
//
// The function returns the following values:
//
//   - utf8 (optional): title.
func (self *SidebarSection) Title() string {
	var _arg0 *C.AdwSidebarSection // out
	var _cret *C.char              // in

	_arg0 = (*C.AdwSidebarSection)(unsafe.Pointer(coreglib.InternObject(self).Native()))

	_cret = C.adw_sidebar_section_get_title(_arg0)
	runtime.KeepAlive(self)

	var _utf8 string // out

	if _cret != nil {
		_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	}

	return _utf8
}

// Insert inserts item at position to self.
//
// If position is -1, or larger than the total number of items in self, the item
// will be appended to the end.
//
// Cannot be used while a model is bound via sidebarsection.BindModel.
//
// The function takes the following parameters:
//
//   - item to insert.
//   - position to insert item at.
func (self *SidebarSection) Insert(item *SidebarItem, position int) {
	var _arg0 *C.AdwSidebarSection // out
	var _arg1 *C.AdwSidebarItem    // out
	var _arg2 C.int                // out

	_arg0 = (*C.AdwSidebarSection)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	_arg1 = (*C.AdwSidebarItem)(unsafe.Pointer(coreglib.InternObject(item).Native()))
	C.g_object_ref(C.gpointer(coreglib.InternObject(item).Native()))
	_arg2 = C.int(position)

	C.adw_sidebar_section_insert(_arg0, _arg1, _arg2)
	runtime.KeepAlive(self)
	runtime.KeepAlive(item)
	runtime.KeepAlive(position)
}

// Prepend prepends item to self.
//
// Cannot be used while a model is bound via sidebarsection.BindModel.
//
// The function takes the following parameters:
//
//   - item to prepend.
func (self *SidebarSection) Prepend(item *SidebarItem) {
	var _arg0 *C.AdwSidebarSection // out
	var _arg1 *C.AdwSidebarItem    // out

	_arg0 = (*C.AdwSidebarSection)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	_arg1 = (*C.AdwSidebarItem)(unsafe.Pointer(coreglib.InternObject(item).Native()))
	C.g_object_ref(C.gpointer(coreglib.InternObject(item).Native()))

	C.adw_sidebar_section_prepend(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(item)
}

// Remove removes item from self.
//
// Cannot be used while a model is bound via sidebarsection.BindModel.
//
// The function takes the following parameters:
//
//   - item to remove.
func (self *SidebarSection) Remove(item *SidebarItem) {
	var _arg0 *C.AdwSidebarSection // out
	var _arg1 *C.AdwSidebarItem    // out

	_arg0 = (*C.AdwSidebarSection)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	_arg1 = (*C.AdwSidebarItem)(unsafe.Pointer(coreglib.InternObject(item).Native()))

	C.adw_sidebar_section_remove(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(item)
}

// RemoveAll removes all items from self.
//
// Cannot be used while a model is bound via sidebarsection.BindModel.
func (self *SidebarSection) RemoveAll() {
	var _arg0 *C.AdwSidebarSection // out

	_arg0 = (*C.AdwSidebarSection)(unsafe.Pointer(coreglib.InternObject(self).Native()))

	C.adw_sidebar_section_remove_all(_arg0)
	runtime.KeepAlive(self)
}

// SetMenuModel sets the context menu model for self's items.
//
// When a context menu is shown for an item, it will be constructed from the
// provided menu model. Use the sidebar::setup-menu signal to set up the menu
// actions for the particular item.
//
// If not set, sidebar:menu-model will be used instead.
//
// The function takes the following parameters:
//
//   - menuModel (optional): menu model.
func (self *SidebarSection) SetMenuModel(menuModel gio.MenuModeller) {
	var _arg0 *C.AdwSidebarSection // out
	var _arg1 *C.GMenuModel        // out

	_arg0 = (*C.AdwSidebarSection)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	if menuModel != nil {
		_arg1 = (*C.GMenuModel)(unsafe.Pointer(coreglib.InternObject(menuModel).Native()))
	}

	C.adw_sidebar_section_set_menu_model(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(menuModel)
}

// SetTitle sets the title of self.
//
// If set, it will be displayed instead of the separator before the section.
//
// The function takes the following parameters:
//
//   - title (optional): title.
func (self *SidebarSection) SetTitle(title string) {
	var _arg0 *C.AdwSidebarSection // out
	var _arg1 *C.char              // out

	_arg0 = (*C.AdwSidebarSection)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	if title != "" {
		_arg1 = (*C.char)(unsafe.Pointer(C.CString(title)))
		defer C.free(unsafe.Pointer(_arg1))
	}

	C.adw_sidebar_section_set_title(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(title)
}
