// Code generated by girgen. DO NOT EDIT.

package adw

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gextras"
)

// #include <stdlib.h>
// #include <adwaita.h>
import "C"

// ActionRowClass: instance of this type is always passed by reference.
type ActionRowClass struct {
	*actionRowClass
}

// actionRowClass is the struct that's finalized.
type actionRowClass struct {
	native *C.AdwActionRowClass
}

// ParentClass: parent class.
func (a *ActionRowClass) ParentClass() *PreferencesRowClass {
	valptr := &a.native.parent_class
	var _v *PreferencesRowClass // out
	_v = (*PreferencesRowClass)(gextras.NewStructNative(unsafe.Pointer(valptr)))
	return _v
}
