// Code generated by girgen. DO NOT EDIT.

package adw

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gextras"
	"github.com/diamondburned/gotk4/pkg/gtk/v4"
)

// #include <stdlib.h>
// #include <adwaita.h>
import "C"

// WrapLayoutClass: instance of this type is always passed by reference.
type WrapLayoutClass struct {
	*wrapLayoutClass
}

// wrapLayoutClass is the struct that's finalized.
type wrapLayoutClass struct {
	native *C.AdwWrapLayoutClass
}

func (w *WrapLayoutClass) ParentClass() *gtk.LayoutManagerClass {
	valptr := &w.native.parent_class
	var _v *gtk.LayoutManagerClass // out
	_v = (*gtk.LayoutManagerClass)(gextras.NewStructNative(unsafe.Pointer(valptr)))
	return _v
}
