// Code generated by girgen. DO NOT EDIT.

package adw

import (
	"github.com/diamondburned/gotk4/pkg/core/gbox"
)

// #include <stdlib.h>
// #include <adwaita.h>
import "C"

//export _gotk4_adw1_AnimationTargetFunc
func _gotk4_adw1_AnimationTargetFunc(arg1 C.double, arg2 C.gpointer) {
	var fn AnimationTargetFunc
	{
		v := gbox.Get(uintptr(arg2))
		if v == nil {
			panic(`callback not found`)
		}
		fn = v.(AnimationTargetFunc)
	}

	var _value float64 // out

	_value = float64(arg1)

	fn(_value)
}
