// Code generated by girgen. DO NOT EDIT.

package adw

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gextras"
	"github.com/diamondburned/gotk4/pkg/gtk/v4"
)

// #include <stdlib.h>
// #include <adwaita.h>
import "C"

// StatusPageClass: instance of this type is always passed by reference.
type StatusPageClass struct {
	*statusPageClass
}

// statusPageClass is the struct that's finalized.
type statusPageClass struct {
	native *C.AdwStatusPageClass
}

func (s *StatusPageClass) ParentClass() *gtk.WidgetClass {
	valptr := &s.native.parent_class
	var _v *gtk.WidgetClass // out
	_v = (*gtk.WidgetClass)(gextras.NewStructNative(unsafe.Pointer(valptr)))
	return _v
}
