// Code generated by girgen. DO NOT EDIT.

package adw

// #include <stdlib.h>
// #include <adwaita.h>
import "C"

// SwipeableInterface: interface for swipeable widgets.
//
// An instance of this type is always passed by reference.
type SwipeableInterface struct {
	*swipeableInterface
}

// swipeableInterface is the struct that's finalized.
type swipeableInterface struct {
	native *C.AdwSwipeableInterface
}
