// Code generated by girgen. DO NOT EDIT.

package adw

// #include <stdlib.h>
// #include <adwaita.h>
import "C"

// ClampLayoutClass: instance of this type is always passed by reference.
type ClampLayoutClass struct {
	*clampLayoutClass
}

// clampLayoutClass is the struct that's finalized.
type clampLayoutClass struct {
	native *C.AdwClampLayoutClass
}
