// Code generated by girgen. DO NOT EDIT.

package adw

import (
	"runtime"
	"unsafe"

	externglib "github.com/diamondburned/gotk4/pkg/core/glib"
	"github.com/diamondburned/gotk4/pkg/gtk/v4"
)

// #cgo pkg-config: libadwaita-1
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <adwaita.h>
// #include <glib-object.h>
import "C"

func init() {
	externglib.RegisterGValueMarshalers([]externglib.TypeMarshaler{
		{T: externglib.Type(C.adw_swipe_tracker_get_type()), F: marshalSwipeTrackerer},
	})
}

// SwipeTracker: swipe tracker used in adw.Carousel and adw.Leaflet.
//
// The AdwSwipeTracker object can be used for implementing widgets with swipe
// gestures. It supports touch-based swipes, pointer dragging, and touchpad
// scrolling.
//
// The widgets will probably want to expose the adw.SwipeTracker:enabled
// property. If they expect to use horizontal orientation,
// adw.SwipeTracker:reversed can be used for supporting RTL text direction.
type SwipeTracker struct {
	*externglib.Object

	gtk.Orientable
}

func wrapSwipeTracker(obj *externglib.Object) *SwipeTracker {
	return &SwipeTracker{
		Object: obj,
		Orientable: gtk.Orientable{
			Object: obj,
		},
	}
}

func marshalSwipeTrackerer(p uintptr) (interface{}, error) {
	val := C.g_value_get_object((*C.GValue)(unsafe.Pointer(p)))
	obj := externglib.Take(unsafe.Pointer(val))
	return wrapSwipeTracker(obj), nil
}

// NewSwipeTracker creates a new AdwSwipeTracker for widget.
func NewSwipeTracker(swipeable Swipeabler) *SwipeTracker {
	var _arg1 *C.AdwSwipeable    // out
	var _cret *C.AdwSwipeTracker // in

	_arg1 = (*C.AdwSwipeable)(unsafe.Pointer(swipeable.Native()))

	_cret = C.adw_swipe_tracker_new(_arg1)
	runtime.KeepAlive(swipeable)

	var _swipeTracker *SwipeTracker // out

	_swipeTracker = wrapSwipeTracker(externglib.AssumeOwnership(unsafe.Pointer(_cret)))

	return _swipeTracker
}

// AllowLongSwipes gets whether to allow swiping for more than one snap point at
// a time.
func (self *SwipeTracker) AllowLongSwipes() bool {
	var _arg0 *C.AdwSwipeTracker // out
	var _cret C.gboolean         // in

	_arg0 = (*C.AdwSwipeTracker)(unsafe.Pointer(self.Native()))

	_cret = C.adw_swipe_tracker_get_allow_long_swipes(_arg0)
	runtime.KeepAlive(self)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// AllowMouseDrag gets whether self can be dragged with mouse pointer.
func (self *SwipeTracker) AllowMouseDrag() bool {
	var _arg0 *C.AdwSwipeTracker // out
	var _cret C.gboolean         // in

	_arg0 = (*C.AdwSwipeTracker)(unsafe.Pointer(self.Native()))

	_cret = C.adw_swipe_tracker_get_allow_mouse_drag(_arg0)
	runtime.KeepAlive(self)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// Enabled gets whether self is enabled.
func (self *SwipeTracker) Enabled() bool {
	var _arg0 *C.AdwSwipeTracker // out
	var _cret C.gboolean         // in

	_arg0 = (*C.AdwSwipeTracker)(unsafe.Pointer(self.Native()))

	_cret = C.adw_swipe_tracker_get_enabled(_arg0)
	runtime.KeepAlive(self)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// Reversed gets whether self is reversing the swipe direction.
func (self *SwipeTracker) Reversed() bool {
	var _arg0 *C.AdwSwipeTracker // out
	var _cret C.gboolean         // in

	_arg0 = (*C.AdwSwipeTracker)(unsafe.Pointer(self.Native()))

	_cret = C.adw_swipe_tracker_get_reversed(_arg0)
	runtime.KeepAlive(self)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// Swipeable: get the widget self is attached to.
func (self *SwipeTracker) Swipeable() Swipeabler {
	var _arg0 *C.AdwSwipeTracker // out
	var _cret *C.AdwSwipeable    // in

	_arg0 = (*C.AdwSwipeTracker)(unsafe.Pointer(self.Native()))

	_cret = C.adw_swipe_tracker_get_swipeable(_arg0)
	runtime.KeepAlive(self)

	var _swipeable Swipeabler // out

	_swipeable = (externglib.CastObject(externglib.Take(unsafe.Pointer(_cret)))).(Swipeabler)

	return _swipeable
}

// SetAllowLongSwipes sets whether to allow swiping for more than one snap point
// at a time.
func (self *SwipeTracker) SetAllowLongSwipes(allowLongSwipes bool) {
	var _arg0 *C.AdwSwipeTracker // out
	var _arg1 C.gboolean         // out

	_arg0 = (*C.AdwSwipeTracker)(unsafe.Pointer(self.Native()))
	if allowLongSwipes {
		_arg1 = C.TRUE
	}

	C.adw_swipe_tracker_set_allow_long_swipes(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(allowLongSwipes)
}

// SetAllowMouseDrag sets whether self can be dragged with mouse pointer.
func (self *SwipeTracker) SetAllowMouseDrag(allowMouseDrag bool) {
	var _arg0 *C.AdwSwipeTracker // out
	var _arg1 C.gboolean         // out

	_arg0 = (*C.AdwSwipeTracker)(unsafe.Pointer(self.Native()))
	if allowMouseDrag {
		_arg1 = C.TRUE
	}

	C.adw_swipe_tracker_set_allow_mouse_drag(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(allowMouseDrag)
}

// SetEnabled sets whether self is enabled.
func (self *SwipeTracker) SetEnabled(enabled bool) {
	var _arg0 *C.AdwSwipeTracker // out
	var _arg1 C.gboolean         // out

	_arg0 = (*C.AdwSwipeTracker)(unsafe.Pointer(self.Native()))
	if enabled {
		_arg1 = C.TRUE
	}

	C.adw_swipe_tracker_set_enabled(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(enabled)
}

// SetReversed sets whether to reverse the swipe direction.
func (self *SwipeTracker) SetReversed(reversed bool) {
	var _arg0 *C.AdwSwipeTracker // out
	var _arg1 C.gboolean         // out

	_arg0 = (*C.AdwSwipeTracker)(unsafe.Pointer(self.Native()))
	if reversed {
		_arg1 = C.TRUE
	}

	C.adw_swipe_tracker_set_reversed(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(reversed)
}

// ShiftPosition moves the current progress value by delta.
//
// This can be used to adjust the current position if snap points move during
// the gesture.
func (self *SwipeTracker) ShiftPosition(delta float64) {
	var _arg0 *C.AdwSwipeTracker // out
	var _arg1 C.double           // out

	_arg0 = (*C.AdwSwipeTracker)(unsafe.Pointer(self.Native()))
	_arg1 = C.double(delta)

	C.adw_swipe_tracker_shift_position(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(delta)
}
