// Code generated by girgen. DO NOT EDIT.

package adw

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gextras"
	externglib "github.com/gotk3/gotk3/glib"
)

// #cgo pkg-config: libadwaita-1
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <adwaita.h>
// #include <glib-object.h>
import "C"

func init() {
	externglib.RegisterGValueMarshalers([]externglib.TypeMarshaler{
		{T: externglib.Type(C.adw_enum_value_object_get_type()), F: marshalEnumValueObjector},
	})
}

type EnumValueObject struct {
	*externglib.Object
}

var _ gextras.Nativer = (*EnumValueObject)(nil)

func wrapEnumValueObject(obj *externglib.Object) *EnumValueObject {
	return &EnumValueObject{
		Object: obj,
	}
}

func marshalEnumValueObjector(p uintptr) (interface{}, error) {
	val := C.g_value_get_object((*C.GValue)(unsafe.Pointer(p)))
	obj := externglib.Take(unsafe.Pointer(val))
	return wrapEnumValueObject(obj), nil
}

func (self *EnumValueObject) Name() string {
	var _arg0 *C.AdwEnumValueObject // out
	var _cret *C.char               // in

	_arg0 = (*C.AdwEnumValueObject)(unsafe.Pointer(self.Native()))

	_cret = C.adw_enum_value_object_get_name(_arg0)

	var _utf8 string // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))

	return _utf8
}

func (self *EnumValueObject) Nick() string {
	var _arg0 *C.AdwEnumValueObject // out
	var _cret *C.char               // in

	_arg0 = (*C.AdwEnumValueObject)(unsafe.Pointer(self.Native()))

	_cret = C.adw_enum_value_object_get_nick(_arg0)

	var _utf8 string // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))

	return _utf8
}

func (self *EnumValueObject) Value() int {
	var _arg0 *C.AdwEnumValueObject // out
	var _cret C.int                 // in

	_arg0 = (*C.AdwEnumValueObject)(unsafe.Pointer(self.Native()))

	_cret = C.adw_enum_value_object_get_value(_arg0)

	var _gint int // out

	_gint = int(_cret)

	return _gint
}
