// Code generated by girgen. DO NOT EDIT.

package adw

// #include <stdlib.h>
// #include <adwaita.h>
import "C"

// ClampScrollableClass: instance of this type is always passed by reference.
type ClampScrollableClass struct {
	*clampScrollableClass
}

// clampScrollableClass is the struct that's finalized.
type clampScrollableClass struct {
	native *C.AdwClampScrollableClass
}
