// Code generated by girgen. DO NOT EDIT.

package adw

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gextras"
	"github.com/diamondburned/gotk4/pkg/gtk/v4"
)

// #include <stdlib.h>
// #include <adwaita.h>
import "C"

// ButtonContentClass: instance of this type is always passed by reference.
type ButtonContentClass struct {
	*buttonContentClass
}

// buttonContentClass is the struct that's finalized.
type buttonContentClass struct {
	native *C.AdwButtonContentClass
}

func (b *ButtonContentClass) ParentClass() *gtk.WidgetClass {
	valptr := &b.native.parent_class
	var _v *gtk.WidgetClass // out
	_v = (*gtk.WidgetClass)(gextras.NewStructNative(unsafe.Pointer(valptr)))
	return _v
}
