// Code generated by girgen. DO NOT EDIT.

package adw

import (
	"runtime"
)

// #include <stdlib.h>
// #include <adwaita.h>
import "C"

// Lerp computes the linear interpolation between a and b for t.
//
// The function takes the following parameters:
//
//    - a: start.
//    - b: end.
//    - t: interpolation rate.
//
// The function returns the following values:
//
//    - gdouble: computed value.
//
func Lerp(a, b, t float64) float64 {
	var _arg1 C.double // out
	var _arg2 C.double // out
	var _arg3 C.double // out
	var _cret C.double // in

	_arg1 = C.double(a)
	_arg2 = C.double(b)
	_arg3 = C.double(t)

	_cret = C.adw_lerp(_arg1, _arg2, _arg3)
	runtime.KeepAlive(a)
	runtime.KeepAlive(b)
	runtime.KeepAlive(t)

	var _gdouble float64 // out

	_gdouble = float64(_cret)

	return _gdouble
}
