// Code generated by girgen. DO NOT EDIT.

package adw

// #include <stdlib.h>
// #include <adwaita.h>
import "C"

// ViewSwitcherBarClass: instance of this type is always passed by reference.
type ViewSwitcherBarClass struct {
	*viewSwitcherBarClass
}

// viewSwitcherBarClass is the struct that's finalized.
type viewSwitcherBarClass struct {
	native *C.AdwViewSwitcherBarClass
}
