// Code generated by girgen. DO NOT EDIT.

package adw

// #include <stdlib.h>
// #include <adwaita.h>
import "C"

// ShortcutsItemClass: instance of this type is always passed by reference.
type ShortcutsItemClass struct {
	*shortcutsItemClass
}

// shortcutsItemClass is the struct that's finalized.
type shortcutsItemClass struct {
	native *C.AdwShortcutsItemClass
}
